services:
  expense-tracker:
    container_name: expense-tracker
    build:
      context: .
      args:
        NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN}
    ports:
      - "8084:8084"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8084
    env_file:
      - .env
